version: "3.9"

services:

  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env  # Use the .env file for environment variables
    environment:
      MYSQL_DATABASE: migroscouriertrackingdatabase
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - migroscouriertrackingNetwork


  migroscouriertracking:
    image: 'migroscouriertracking:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migroscouriertracking
    restart: on-failure
    env_file:
      - .env  # Use the .env file for environment variables
    ports:
      - "1226:1226"
    environment:
      - server.port=1226
      - spring.datasource.username=${DATABASE_USERNAME}
      - spring.datasource.password=${DATABASE_PASSWORD}
      - CASE_DB_IP=database
      - CASE_DB_PORT=3307
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3307/migroscouriertrackingdatabase
    depends_on:
      - database
    networks:
      - migroscouriertrackingNetwork

networks:
  migroscouriertrackingNetwork: